spring:
  application:
    name: learn-jpa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 369369
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true