server:
  port: 9006
spring:
  application:
    name: learn-tx
  datasource:
    password: 369369
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/test